### ISSUE TITLE
how to not parse date-looking-strings as dates, but as strings?

### ISSUE THREAD

**Issue by coolaj86** [nodeca/js-yaml#161]
Is there a way to turn off the datetime parsing?

I have a bunch of date and time strings, but they're meant for literal presentation as strings, not for interpretation as date objects.

**Comment by dervus** [comment]
There are two ways.

- You can [explicitly specify that these are plain strings at source level](http://nodeca.github.io/js-yaml/#yaml=LSAhIDIwMDEtMTItMTVUMDI6NTk6NDMuMVoKLSAnMjAwMS0xMi0xNVQwMjo1OTo0My4xWicKLSAiMjAwMS0xMi0xNVQwMjo1OTo0My4xWiI=).

- You can [use Core, JSON, or Failsafe schemas](https://github.com/nodeca/js-yaml#safeload-string---options-) instead of the default one. These schemas are pretty limited, so you may want to [define you own schema](https://github.com/nodeca/js-yaml/blob/master/examples/custom_types.js) based on them:
```javascript
var SCHEMA = yaml.Schema.create(yaml.CORE_SCHEMA, [ /* additional types */ ])
```

**Comment by coolaj86** [comment]
For reference, I was able to get it working like this:

```javascript
var YAML = (window.jsyaml || require('js-yaml'))
  , schema
  ;

schema = YAML.Schema.create(YAML.CORE_SCHEMA, []);
YAML.load('date: 2006-03-06 06:38:00 -07:00', { schema: schema });
```

**Comment by ixti** [comment]
My two cents. IMHO strings in YAML should be strings. If you need to have something that might be interpreted as non-string but you need it to be string, either explicitly set type, or implicitly (use quotes):

``` yaml
---
explicit: !!str 2015-02-03
implicit: "2015-02-03"
```
