### ISSUE TITLE
Any way to encode multi-line strings with `|`

### ISSUE THREAD

**Issue by isaacs** [nodeca/js-yaml#171]
js-yaml parses this just fine:

```yaml
m: |
  multi
  line
  string
```

```
> yaml.safeLoad('m: |\n      multi\n      line\n      string')
{ m: 'multi\nline\nstring\n' }
```

When I re-encode that value back to yaml, I'd like to use the `|` indented style for multi-line strings, because it is much more readable than the JSON-style encoding.

```
> yaml.safeDump({ m: 'multi\nline\nstring\n' })
'm: "multi\\nline\\nstring\\n"\n'
> console.log(_)
m: "multi\nline\nstring\n"
```

1. Is there an option to tell js-yaml to prefer `|` to quoted strings for multi-line strings?
2. If not, would you be open to a patch that does this?

**Comment by puzrin** [comment]
> Is there an option to tell js-yaml to prefer | to quoted strings for multi-line strings?

No.

> If not, would you be open to a patch that does this?

We have very old issue #66, that text scalars should be dumped better

So, yes, we are open to improvements in this area, but i'd like to avoid "partial hacks". It's better to implement `|` at least with `>`.

**Comment by isaacs** [comment]
Good to know.  I'll dig into this if I get some time.

I apologize, I'm a yaml noob.  Can you point me to the difference in semantics between `|` and `>`?

**Comment by puzrin** [comment]
http://www.yaml.org/spec/1.2/spec.html#id2760844 - the first paragraph. And search word "chomping", for `+` & `-` modifiers description.

Also seems that autoquoting support still needed for multilines, to make non trimmable spaces visible for humans: `foo\n    bar   \nbaz`.

PS. if you ever deсide to support `package.yml` instead of `package.json` in npm, i promiss to set aside all plans and implement any features in js-yaml you wish, LOL.

**Comment by isaacs** [comment]
Awesome, thanks for the link.

It's unlikely that we'll add `package.yml` support to npm.  But I am finding js-yaml very nice for the refactor of node-tap.

**Comment by puzrin** [comment]
Closing as #66 dupe?

**Comment by isaacs** [comment]
Yes, that seems reasonable.  It is about the same as #66.
