### ISSUE TITLE
Cannot dump no values with comments

### ISSUE THREAD

**Issue by acierto** [nodeca/js-yaml#196]
It is not possible currently to achieve such result:

common:
    apiKey:    # This is a required field

**Comment by dervus** [comment]
I don't understand what do you want to achieve. JS-YAML dumps given data exactly as is.

**Comment by acierto** [comment]
If now I try to dump the object it will write to the file:

common:
     apiKey: "# This is a required field"

I want 

common:
     apiKey:  # This is a required field

So with another words, js-yaml always put value in quotes

**Comment by dervus** [comment]
You want to add comments to the dump?

**Comment by acierto** [comment]
yes, now I'm missing this functionality in this library. I want to create a configuration file where some fields don't have any values and provide a comment for the user to fill it in. But instead I have quoted value :(

**Comment by dervus** [comment]
I think JS-YAML is not suitable for such tasks by design. It targets to fast data (de)serialization and therefore misses fine configuration. I mean that in order to generate a dump that look like it was written by a human, you will need AST access, which JS-YAML cannot provide. It is possible to add option that will accept object of the same structure as data to dump and write it's values as comments, but I don't think that it will have much sense, and I don't think I like the idea of adding such weird stuff to the library.

@puzrin What do you think about this?

**Comment by puzrin** [comment]
That's out of this library scope.

**Comment by lipis** [comment]
Can we reevaluate the need of supporting comments?! It would be great, because by doing that it can be used in Prettier to start supporting and formatting YAML files with it: https://github.com/prettier/prettier/issues/3017

**Comment by puzrin** [comment]
No, because that requires completely different architecture, and this one is focused on speed.

**Comment by lipis** [comment]
I have no idea how it's done.. but I'm sure there is a way to fix it without compromising speed.. it's 2017 :)

**Comment by puzrin** [comment]
Development is clear technical process, not religion. We can operate only materializable things, beliefs are not enougth to take into account :)

**Comment by lipis** [comment]
thanks for the info.. I wasn't aware.. :P
