### ISSUE TITLE
Comments and escaping in plain style

### ISSUE THREAD

**Issue by stevage** [nodeca/js-yaml#212]
I'm not sure if you're aiming for strict compliance with the YAML spec, but by my reading of the spec ("The plain (unquoted) style has no identifying indicators and provides no form of escaping...Plain scalars must never contain the “: ” and “ #” character combinations."), this should be illegal:

```
- foo:
    my \# commented
    string
```

Yet JS-YAML treats the \ as an escape. 

Interestingly, it doesn't allow `my \: colon`, yet accepts any character after a colon, including #: "

```
- foo:
    my :# non-commented
    colon
```

**Comment by dervus** [comment]
`: ` (colon, whitespace) is used to denote key-value pair.
` #` (whitespace, sharp) is used to denote comment.
Other combinations are considered scalar content. I can't reproduce any escaping in plan scalars using `\`. Also, you example with `my \: colon` is most likely broken because **it is** a key-value pair starting implicit mapping, and it must be continued as a mapping on the next line.

**Comment by stevage** [comment]
Oh! I totally missed the spaces in the ": " and " #" text I quoted. And yes, my \: colon example was incorrect - only works on one line, and the \ can be anything.

Sorry about that.
