### ISSUE TITLE
Don't include esprima in the browser bundle

### ISSUE THREAD

**Issue by ArtskydJ** [nodeca/js-yaml#230]
In [function.js](https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/js/function.js) there is a try/catch around a require statement. Browserify will find that require statement and still include esprima in the browser bundle.

Using browserify, you can use the ["browser" field](https://github.com/substack/browserify-handbook#browser-field) like this...
```json
  "browser": {
    "esprima": false
  },
````
...to make `require('esprima')` return an empty object in the browser.

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/Makefile#L86

It's not uncluded. Or do you mean improve browserify support for parent packages?

**Comment by ArtskydJ** [comment]
Yeah, when a parent package includes js-yaml, then esprima gets pulled in.

I guess I could add the `-x esprima` option to any browserify npm script that has js-yaml as a (sub)dependency, but it's a bit unintuitive, and it is documented that [esprima won't be included in bundled versions](https://github.com/nodeca/js-yaml#bundled-yaml-library-for-browsers).

**Comment by puzrin** [comment]
Ok. Then, please remove that option from makefile for consistency, and rename commit as "Improve browserify support"

**Comment by ArtskydJ** [comment]
I might have a chance to make that PR this evening...

**Comment by TehShrike** [comment]
It looks like `make browserify` builds the distribution files.

Is it accurate to say that `make browserify` *uses* browserify to build the distribution files, but doesn't build files that are meant to be included by browserify (since browserify will naturally include whatever file node.js would)?

That's how it appears to me.  If this is accurate, then I suggest that the name of the makefile section be renamed from "browserify" to "dist" or something similar.

Feel free to correct me though, I'm not familiar with makefile conventions.

I don't think this naming suggestion interferes with anything else being dealt with in the currently associated pull requests, so feel free to ignore it and accept the other changes as-is.

**Comment by puzrin** [comment]
@TehShrike you are right, `make dist` could be better, but that's not principal question. I get used to `make browserify` and see no reasons to change habbits until next big changes :)

**Comment by TehShrike** [comment]
Fair enough! :-)

Glad to see this esprima inclusion fixed for browserify, it will help Noddity quite a bit. https://github.com/TehShrike/noddity/issues/27
