### ISSUE TITLE
Support for octal integers

### ISSUE THREAD

**Issue by ghost** [nodeca/js-yaml#27]
Support for octal integers

```
octal: 0o14
```

**Comment by trevorr** [comment]
Should this be revisited, since YAML 1.2 changed the octal prefix from "0" to "0o"?

https://yaml.readthedocs.io/en/latest/pyyaml.html#defaulting-to-yaml-1-2-support
http://www.yaml.org/spec/1.2/spec.html#id2761509

**Comment by puzrin** [comment]
Agree, worth to fix.

**Comment by puzrin** [comment]
I think, nobody cares about octals, but... Question is, how much should we care about backward compatibility.

**Comment by trevorr** [comment]
Does js-yaml recognize the `%YAML` directive for detecting the version? If pre-1.2 support is desired, it could be maintained with that.

Incidentally, I noticed this issue because I'm hitting an incompatibility between js-yaml and raml-1-parser when trying to read and write (i.e. round-trip) a RAML document. For example, take this input:

```yaml
example:
  seq1: '000123'
  seq2: '000999'
```

If I dump it back out with js-yaml, I get this:

```yaml
example:
  seq1: '000123'
  seq2: 000999
```

The quotes go away for `seq2` because "9" isn't a valid octal digit. However, raml-1-parser interprets `000999` as a number, which fails to validate as a string. I think raml-1-parser's fork of js-yaml (yaml-ast-parser) is in error, because it expects the YAML 1.2 "0o" prefix for octal, and uses an overly simplistic `/^[-+]?[0-9]+$/` regex for decimal.

**Comment by puzrin** [comment]
> Does js-yaml recognize the %YAML directive for detecting the version?

No. 1.1 don't worth efforts to support.

I'd suggest to support both in reader but dump in new format. Then deprecate old format in next major version. Don't know if it worth to bump major version right now.

**Comment by DavidBiesack** [comment]
Any plans to fix this? I just spent quite a while trying to figure out why js-yaml was converting strings values to numbers

```
$ echo 'id: "01234567"' | js-yaml | js-yaml
id: '01234567'
$ echo 'id: "012345678"' | js-yaml | js-yaml
id: 012345678
```

since YAML 1.2 requires `0o` prefix. (The name of this project is "JS-YAML - YAML 1.2 parser" after all... )

I also get the same problem using the Javascript `yaml.safeDump(document, { lineWidth: -1, indent: 2, noCompatMode: true })` which I had hoped would follow YAML 1.2

**Comment by DavidBiesack** [comment]
@puzrin This is emitted as a number but must be quoted

```
echo '{ "id": "012345678"}' | js-yaml 
```

returns
```
id: 012345678
```
which is incorrect - other YAML parsers (adhering the [YAML 1.2 10.3.2. Tag Resolution](https://yaml.org/spec/1.2/spec.html#id2805071)) will parse this as a base 10 integer (that input matches the regex `[-+]? [0-9]+`). 

It is invalid to remove the quotes; this is not a string.

ys-yaml should yield

```
id: '012345678'
```

In fact, ys-yaml also incorrectly parses this as a number:

```
echo 'id: 012345678' | js-yaml 
{
  "id": "012345678"
}
```

The input 012345678 is not an octal number in YAML 1.2 - Octals must have `0o` prefix, so this should match the YAML syntax for an `int` not a `str`.

**Comment by puzrin** [comment]
If i understand right, current issue was about loader support, but you means string quoting in dumper.

Finally, i understand why 1.2 spec allows heading zeroes for int :)

**Comment by puzrin** [comment]
Fixed by https://github.com/nodeca/js-yaml/commit/19185199e0cc6357869afde7194bb2239ef67917
