### ISSUE TITLE
Unexpected indent

### ISSUE THREAD

**Issue by ysmood** [nodeca/js-yaml#292]
``` js
var yaml = require('js-yaml');

yaml.load('|2\n  a\n  b'); // => ' a\n b\n'
```

It will output `a\n b\n`. It should output `a\nb\n`.

**Comment by eemeli** [comment]
Actually, this is not a bug but intended behaviour. The top level of a YAML document is considered to be at the -1 level so that e.g. `|\na\nb\n` doesn't cause an error but is parsed as `'a\nb\n'`. Therefore if a top-level scalar block header includes a number, it should be one more than the expected number of indentation spaces.

This behaviour also matches that of other libraries:
```js
import YAML from 'yaml'

YAML.parse('|2\n  a\n  b') // => ' a\n b\n'
```

**Comment by puzrin** [comment]
Close as not a bug
