### ISSUE TITLE
safeLoad('') returns undefined

### ISSUE THREAD

**Issue by pelotom** [nodeca/js-yaml#326]
As noted [here](https://github.com/nodeca/js-yaml/issues/325#issuecomment-276494473), `undefined` is not valid JSON or YAML, so it seems like `safeLoad()` should never return `undefined`. If the empty string is invalid YAML (a point I'm not sure about), `safeLoad('')` should throw an exception.

**Comment by puzrin** [comment]
That's a special case, not a bug.

**Comment by pelotom** [comment]
Why does a YAML parser return invalid YAML as a special case?

**Comment by puzrin** [comment]
Parser does NOT return yaml. It returns data. IMHO you mix different terms and this cause confusion. I can't talk just for fun, can't change parser just for fun. Just show reference to spec about empty strings instead of pure statements, or reference to well known implementations. And we can continue with something constructive.

**Comment by pelotom** [comment]
I'm not trying to be difficult, just trying to understand. What do you mean that it returns data? What kind of data does a YAML parser returns if not YAML?

**Comment by puzrin** [comment]
Yaml is just a text markup format, to describe data structures. You can describe such structures in many other ways. Data structures, supported by yaml, are specified in yaml spec. This project is just a yaml spec implementation, we stay aside of spec discussion and so on. If you wish to report that parser returns wrong value on empty string, you are expected to read spec before and point to exact place, explaining that empty string should produce another result.
