### ISSUE TITLE
Support ES symbols

### ISSUE THREAD

**Issue by js-choi** [nodeca/js-yaml#359]
There’s a relatively new standard [primitive data type][] in JavaScript: the [symbol][]. Since JavaScript engines have added support for symbols several years ago, and since they are part of the standard ECMAScript specification, their use has been progressively increasing.

JS-YAML should support `dump`ing and `load`ing data containing symbols. They would probably look like `!!js/symbol description` and `!!js/symbolFor globalKey`. They would also probably be safe for `DEFAULT_SAFE_SCHEMA`.

I ran into this lack of support myself when using [Node-Tap](https://github.com/tapjs/node-tap): `t.strictEqual(Symbol(''), Symbol(''))` causes an `unacceptable kind of an object to dump [object Symbol]` error to occur in `writeNode` (`node_modules/js-yaml/lib/js-yaml/dumper.js:738:13`).

[primitive data type]: https://developer.mozilla.org/en-US/docs/Glossary/Primitive
[symbol]: https://developer.mozilla.org/en-US/docs/Glossary/symbol

**Comment by puzrin** [comment]
You can extend it via custom types if you wish. I see no reasons to have it in mainstream.

**Comment by polomsky** [comment]
Symbol is not a custom object, but the standard one (same as e.g. RegExp, Date which are supported). I am voting for that feature.

**Comment by isaacs** [comment]
@puzrin I can't quite figure out how to define Symbol as a custom type, since `instanceof` always returns false for symbols.  Is there another way to get the dumper to recognize an object besides a class reference?

I really think this deserves more consideration.  Symbols aren't normal JavaScript objects, and don't obey the normal rules.  They can be used as keys on objects, for example, and despite the fact that `mySymbol.__proto__ === Symbol.prototype`,  `mySymbol instanceof Symbol` will return false.  Symbols are effectively like strings that exhibit Object identity.  They're a "magic" type in the language.

**Comment by puzrin** [comment]
@isaacs may be i miss something... As far as i remember, type definition allows custom function for value type check.

https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/js/regexp.js#L58

If something is not enougth - i'm ok about architecture fixes, but against adding JS-specific syntax deviations into core.
