### ISSUE TITLE
add_multi_constructor equivalent / unknown tag handler

### ISSUE THREAD

**Issue by akdor1154** [nodeca/js-yaml#385]
In PyYAML, I can use the `add_multi_constructor` feature to allow me to define a constructor for multiple tags. I am using it to handle any unknown tags. For example, I could use this to deserialize the document
```yaml
thing1: !someTag asdf
thing2: !someOtherTag fdsa
```

into the JS structure
```js
{
  thing1: UnknownTag { tag: 'someTag', value: 'asdf' },
  thing2: UnknownTag { tag: 'someOtherTag', value: 'fdsa' }
}
```

and be able to re-serialize that structure back into equivalent yaml.

My use case is to read and modify a tiny part of a big yaml file that has a bunch of domain-specific tags in it. I don't care how the tags are resolved as I'm not reading that part of the file, but currently with js-yaml I can't read it at all because to parse the file in the first place results in an unknown tag error. Even if I set it to skip unknown tags, I can't re-serialize the modified docjument.

This is fine with PyYAML as I can use `add_multi_constructor` as defined above to handle any unknown tags, but as far as I can tell this behvaiour is impossible to achieve with js-yaml.

**Comment by Thom1729** [comment]
This would be extremely useful to me. I'm processing AWS CloudFormation templates with js-yaml. CloudFormation uses a number of tags as macros, e.g. `!Ref`. These tags need to roundtrip when I load and dump the file.

Currently, in order to do that, I have to hard-code a list of tags used by AWS and define a type for each tag, for each kind of node (because some AWS tags are used for more than one kind of node). This is a pain, it will break if AWS starts supporting additional tags, and it makes otherwise-simple processing code harder to understand. This feature request would drastically simplify this task.

**Comment by TFarla** [comment]
I'm interested in this feature as well. Currently working on deserializing various yaml scripts we get from customers. They're predictable but we could encounter an unknown tag

**Comment by rlidwka** [comment]
Added in https://github.com/nodeca/js-yaml/commit/73ef02cfcb63d9f1c5932dadc1fc35f05a25fdbc (currently in `dev` branch).

See an example how to do it here:
https://github.com/nodeca/js-yaml/blob/a0d0caa5aa0f5354fefa9c637cfb7c4c17ef7d02/examples/handle_unknown_types.js
