### ISSUE TITLE
Ability to output quoted numbers as strings, preserving the original quotes.

### ISSUE THREAD

**Issue by scottp** [nodeca/js-yaml#530]
I have read the closed bugs #394 and #512 and still can't work out any solution to leave a quoted string with a 0 and 8 in it. Here are two examples showing the output as well.

```
# Example that works
node -e "console.log(require('js-yaml').safeDump({a: '017'}))"
a: '017'

# Example using single quotes
node -e "console.log(require('js-yaml').safeDump({a: '018'}))"
a: 018

# Example using double quotes
node -e 'console.log(require("js-yaml").safeDump({a: "018"}))'
a: 018
```

All I'm looking for is a way to leave quoted string always quoted, even if that requires a special character.

**Comment by cutephoton** [comment]
Interesting issue. I was so focused on 018 thinking it had been mistakenly cast as an integer. Turns out, since it is not a valid number the dumper drops the quotes as redundant. It does not provide a direct means to control the behaviour. But... it is possible to inhibit/defeat indirectly.

https://github.com/nodeca/js-yaml/blob/d6983dd4291849b2854e8d26e1beb302edfd4c76/lib/js-yaml/type/int.js#L20

Copy this file. Have this function (resolveYamlInteger) always return true. Do not use this to load YAML files for obvious reason. It looks a bit like this...

```
const MyBadInt = new Type('tag:yaml.org,2002:int', ...);
const myDumpsSchema = new Schema({
    include: [SchemaUsedToLoad (or a default)], implicit:[MyBadInt]
});
console.log(safeDump({a: '018'},{schema:myDumpsSchema}));
```

I hope that helps. My testing was pretty limited so you may find this may have side effects. The dumper's behaviour appears reasonable though.

**Comment by DavidBiesack** [comment]
This is really a dup of #27

**Comment by cutephoton** [comment]
It's not really a bug. It conforms to the standard.
