### ISSUE TITLE
writer: dump date without time

### ISSUE THREAD

**Issue by Giszmo** [nodeca/js-yaml#569]
A yaml property `date: 2020-07-22` should survive the round trip but I get `date: 2020-07-11T00:00:00.000Z`.

**Comment by rlidwka** [comment]
> A yaml property `date: 2020-07-22` should survive the round trip

 - `load(dump(xxx))` - any data should survive this round-trip
 - `dump(load(xxx))` - but this round-trip is not guaranteed

the reason is: both `date: 2020-07-22` and `date: 2020-07-22T00:00:00.000Z` are represented as the same date object - `new Date(1595376000000)` - in javascript, and it has no information left about original yaml formatting

and given the choice of how to dump a particular date, I think it's better to go with more explicit representation

**Comment by Giszmo** [comment]
While it's really annoying for my yaml use, I see your point.

A date-String ending in `T00:00:00.000Z` is arguably redundant, too though and could by the same logic be pruned.

**Comment by rlidwka** [comment]
Can you fix it for your own app with a hack similar to this?: https://github.com/nodeca/js-yaml/issues/570#issuecomment-662824086

I wonder if there should just be a public api to customize dumper output.

**Comment by Giszmo** [comment]
I think if this is not of broader interest, the issue can be closed. If there was broader interest, I might make a PR to remove "trailing zeros" in Date dumps. Doesn't feel terribly complicated and would be in line with trailing zeros vanishing for floats, right? ;)

**Comment by rlidwka** [comment]
> Doesn't feel terribly complicated and would be in line with trailing zeros vanishing for floats, right?

Floats are easy. If you write number `42` while being in europe, you don't usually expect some american computer to parse it as `42.3` (and switch to `42.4` during summer). 😕 

`T00:00:00.000` may be redundant, but `Z` is not. Need to carefully check yaml spec to see what happens if you miss it...

**Comment by Giszmo** [comment]
omg, locales are fun :D

You win
