### ISSUE TITLE
writer: provide option where null values are just empty.

### ISSUE THREAD

**Issue by Giszmo** [nodeca/js-yaml#570]
If empty gets read as `null`, it should at least optionally be possible to also write `null` as empty.

```
$ dump(load("something: "))
something: null
```

**Comment by puzrin** [comment]
That's valid, according to yaml spec

**Comment by Giszmo** [comment]
I think I could help myself but it looks hacky:

```
  const schema = yaml.DEFAULT_SAFE_SCHEMA
  schema.compiledTypeMap.scalar['tag:yaml.org,2002:null'].represent.lowercase = function() { return '' }
  file.write(`---
${yaml.safeDump(header, {
  noArrayIndent: true,
  schema: schema
})}
...
```

**Comment by rlidwka** [comment]
Fixed in https://github.com/nodeca/js-yaml/commit/421ed226e36e0f834335c9ddae5551b70c6659af (located in **dev** branch at the moment).

Normally, I'd advise to override `null` schema. But some other parsers (namely, `psych` and `ruamel.yaml`) serialize null this way, so it makes sense to at least provide an option.
