### ISSUE TITLE
Sort order does not work on mixed numeric/string keys

### ISSUE THREAD

**Issue by extremeheat** [nodeca/js-yaml#622]
```yml
remaps:
  'a': value 1
  '1': value 2
  'b': value 3
  'c': value 4
  ```

gets mapped to `{ remaps: { '1': 'value 2', a: 'value 1', b: 'value 3', c: 'value 4' } }`

instead of `{"remaps": { "a": "value 1", "b": "value 2", "c": "value 3" }}`

even with `sortKeys` set to false (default) is there any way to get this to work ? This is probably a JS side effect, but needed for interop with other languages.

Works fine on https://yaml-online-parser.appspot.com/ for example
```json
{
  "remaps": {
    "a": "value 1", 
    "1": "value 2", 
    "c": "value 4", 
    "b": "value 3"
  }
}
```

there was some discussion in #503 about using a JS Map for deterministic ordering, is there an easy place to change this in the code?

**Comment by BurtHarris** [comment]
This is expected behavior.   ECMAScript 2015 specification (and later versions) requires that keys of an object are enumerated in three groups: 
1. integer keys in ascending order, 
2. string keys in the order added, 
3. and finally, symbol typed keys in the order added.   

Note that only non-negative integers fit into the first category because the object behaves like a sparse array.   While you can have object keys of negative or floating-point values, they are treated as strings in the above ordering.

Older versions of most JavaScript engines behaved this same way; it just wasn't officially required.   Speaking of which, YAML's definition is clear that the order of keys does not matter and can be reordered.

**Comment by rlidwka** [comment]
duplicate of https://github.com/nodeca/js-yaml/issues/329

it's hard to do this without breaking backward compatibility, so postponed for now :(
