### ISSUE TITLE
Could you help remove the vulnerability introduced in the package?

### ISSUE THREAD

**Issue by paimon0715** [nodeca/js-yaml#628]
Hi @Puzrin @rlidwka,there is a vulnerability introduced in your package 
### Issue

   1 vulnerability (medium severity) is introduced in **_js-yaml_**:
Vulnerability **CVE-2021-23358** (medium severity) is detected in package **_underscore_**(versions:>=1.3.2 <1.12.1,>=1.13.0-0 <1.13.0-2):[https://snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984](https://snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984)
   The above vulnerable package is referenced by **_js-yaml_** via:
`js-yaml@2.0.5 ➔ argparse@0.1.16 ➔ underscore@1.7.0`

### Solution
Since **_js-yaml@2.0.*_** is transitively referenced by **1745** downstream projects (e.g., [uglify 0.1.5](https://www.npmjs.com/package/uglify) (latest version),[grunt-express 1.4.1](https://www.npmjs.com/package/grunt-express) (latest version), [wix-gruntfile 0.1.1235](https://www.npmjs.com/package/wix-gruntfile)  (latest version), [grunt-phplint 0.1.0](https://www.npmjs.com/package/grunt-phplint) (latest version), [junit-reporter 0.0.2](https://www.npmjs.com/package/junit-reporter)(latest version)), 

**_js-yaml@3.0.*_** is referenced by **263** downstream projects (e.g., [align-yaml 0.1.8](https://www.npmjs.com/package/align-yaml) (latest version), [grunt-assemble 0.6.3](https://www.npmjs.com/package/grunt-assemble) (latest version), [grunt-yaml 0.4.2](https://www.npmjs.com/package/grunt-yaml) (latest version), [parallel-cucumber 1.1.0](https://www.npmjs.com/package/parallel-cucumber) (latest version), [Template 0.17.5](https://www.npmjs.com/package/Template) (latest version)),

**_js-yaml@2.1.*_** is referenced by **247** downstream projects (e.g.,[yaml-config 0.3.0](https://www.npmjs.com/package/yaml-config) (latest version), [audit-badge 1.0.0](https://www.npmjs.com/package/audit-badge) (latest version), [yaml-brunch 1.0.1](https://www.npmjs.com/package/yaml-brunch) (latest version), [swagger-express 1.0.5](https://www.npmjs.com/package/swagger-express) (latest version), [referer-parser 0.0.3](https://www.npmjs.com/package/referer-parser) (latest version)),

If **_js-yaml_** removes the vulnerable package from the above versions, then its fixed versions can help downstream users decrease their pain.It’s kind of you to update packages in these versions.

### Fixing suggestions

(1）In **_js-yaml@2.0.*_**, you can kindly try to perform the following upgrade (not crossing  its major versions):
`argparse ~ 0.1.11 ➔ 0.1.0`;  

(2）In **_js-yaml@3.0.*_**, you can kindly try to perform the following upgrade (not crossing  its major versions):
`argparse ~ 0.1.11 ➔ 0.1.0`;  

(3）In **_js-yaml@2.1.*_**, you can kindly perform the following upgrade (not crossing its major versions):
`argparse ~ 0.1.11 ➔ 0.1.0`;  

**Note:**
_argparse@0.1.0 directly depends on underscore@1.3.1(a version without vulnerability CVE-2021-23358)_

Thank you for your contributions to the downstream users!

Sincerely yours,
Paimon

**Comment by paimon0715** [comment]
A large number of downstream users transitively use js-yaml@2.0.* ,@3.0.*  and @2.1.* via unmaintained packages (the unmaintained packages cannot upgrade js-yaml from 2.0.* ,3.0.* or 2.1.* to the latest version).So if you can kindly release fixed 2.0.* ,3.0.* and 2.1.* versions, the downstream users can avoid introducing the vulnerablity.

**Comment by puzrin** [comment]
I don't like suggested direction. IMO doing hacks for unmaintained packages  not good idea.

Also note, referred vulnerabilities do not affect real package use.

**Comment by paimon0715** [comment]
@puzrin Sorry for confusing you.

The purpose of the fix is not for the unmaintained packages. 
Many actively maintained downstream users reference the vulnerablity via unmaintained packages (cannot update their dependencies).
Since these unmaintained packages reference the lower versions of  js-yaml (@2.0.*,  @2.1.*),
if  js-yaml @2.0.*,  @2.1.* can fix this issue, the vulnerable patches can be automatically propagated into the active downstream projects.

**Comment by puzrin** [comment]
IMO location of unmaintained package in dependency graph does not matter. Someone could start maintain fork or stop use it. If nobody did that for 5 years - let that package die.

**Comment by rlidwka** [comment]
### Understanding the issue

As you've shown above, `underscore` is a dependency of `argparse@1`, a library we used few years ago (before its complete rewrite) **to parse cmdline arguments**.

`argparse` is used when you run `./bin/js-yaml`, it is **not** used when you require() this package.

> Since js-yaml@2.0.* is transitively referenced by 1745 downstream projects

What I'm saying is: when js-yaml is used a transitive dependency, `underscore` **doesn't even get loaded into memory**. So all of these 1745 projects are completely fine, unless one of them invokes js-yaml via child_process (which is so strange that I'd very much like to see why).

### Solution for js-yaml 3.x branch

Latest `js-yaml` version of this branch is 3.14.1, which **doesn't even have underscore as a dependency**. At all. Seriously.

```sh
$ yarn add js-yaml@3
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
└─ js-yaml@3.14.1
info All dependencies
├─ argparse@1.0.10
├─ esprima@4.0.1
├─ js-yaml@3.14.1
└─ sprintf-js@1.0.3
Done in 1.43s.
```

Any js-yaml 3.x version can be upgraded to 3.14.1 safely. That's literally what semver tells you, and you even have a CHANGELOG.md to verify.

And they **should** be upgrading anyways, because we've been fixing real vulnerabilities along the way (those that can actually happen).

### Solution for js-yaml 2.x branch

3.0.0 was released in the year 2013, so God knows anyone who cares would've updated by now.

If you are looking at a project that uses js-yaml@2, it means it hasn't been updated at all for **seven years**. They are gonna have much more serious issues than this one.

But if you still want to use packages that haven't been updated for seven years, as I've explained above, vulnerable code in underscore **won't even get loaded into memory** because it's used exclusively in the CLI.

Thus, whatever CVE validation tool you're using is nothing but a harmless reminder to find a way to update whatever is referencing this package. Wouldn't it do more good if it actually stays this way?

**Comment by rlidwka** [comment]
We currently support security fixes for two branches, `3.x` (latest 3.14.1) and `4.x` (latest 4.1.0).

Please upgrade to one of these versions, otherwise you'd be missing on security fixes (see [changelog](https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md)), including those that CVE weren't created for (3.13.0 might be especially important if you parse untrusted data).

If you have a dependency that still uses `2.x` branch, it means it has been inactive for 7 years. You can find an alternative for it, or create a service for the community by creating a well-maintained fork.

**Comment by paimon0715** [comment]
@rlidwka Got it! Thanks for your answers.
