### ISSUE TITLE
bug in parsing

### ISSUE THREAD

**Issue by geert56** [nodeca/js-yaml#693]
The YAML 1.2.2 spec states:
"Within a block collection, key/value pairs can start immediately following the dash, colon or question mark."
This implies that "a: b: c: d: - 1" is a valid YAML document. js-yaml however issues an error message.

**Comment by ingydotnet** [comment]
That sentence is just a clarification of the context around it.
You've taken it on its own to be an assertion/property of YAML, but it doesn't make sense outside the context at
https://yaml.org/spec/1.2.2/#example-mapping-between-sequences

The point of the sentence is to say that (from the examples that follow the statement) you can do this:
```
? - Detroit Tigers
  - Chicago cubs
: - 2001-07-23
```
instead of this:
```
?
  - Detroit Tigers
  - Chicago cubs
:
  - 2001-07-23
```

and this:
```
- item    : Super Hoop
  quantity: 1
```

instead of this:
```
-
  item    : Super Hoop
  quantity: 1
```

**Comment by ingydotnet** [comment]
For the record, `a: b: c: d: - 1` is invalid YAML and this is not a "bug i n parsing".

YAML doesn't support compact block mappings
```
key: key: value   # wrong
```
even though it does support compact block sequences:
```
- - - value
# same as
-
  -
    - value
```
and also compact block mapping in sequence:
```
- - key1: value1
    key2: value2
# same as
-
  -
    key1: value1
    key2: value2
```

**Comment by geert56** [comment]
Thanks for the clarifications. In my honest opinion, the spec could have been a bit more precise and express syntax in a more conventional, formal way. Alas, we shall have to live with it.
