### ISSUE TITLE
Quotes not preserved when reading YAML, then dumping it.

### ISSUE THREAD

**Issue by aaronscribner** [nodeca/js-yaml#711]
If you read YAML and dump it, the content changes.

It fails to preserve the YAML and does not respect quoted values.

How I can have it keeps the quotes for the values in the YAML that are quoted, but leave the rest alone?

I have this

  ${application}:
    image: ${DOCKER_REGISTRY-}${application}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: "${dockerfile}"
      args:
        - IMG_REGISTRY=${REGISTRY:-mcr.microsoft.com}
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-https://*:4443}
    ports:
      - "43301:${EXPOSED_PORT:-4443}"
    volumes:
      - ~/.aspnet/https:/https:ro

Looks like this when I force quotes, which is incorrect

  - budgets:
      image: '${DOCKER_REGISTRY-}budgets:${IMAGE_TAG}'
      build:
        context: '.'
        dockerfile: 'Budgets/src/Budgets.Api/Dockerfile'
        args:
          - 'IMG_REGISTRY=${REGISTRY:-mcr.microsoft.com}'
      environment:
        - 'ASPNETCORE_URLS=${ASPNETCORE_URLS:-https://*:4443}'
      ports:
        - '43301:${EXPOSED_PORT:-4443}'
      volumes:
        - '~/.aspnet/https:/https:ro'

Expected output

  - budgets:
      image: ${DOCKER_REGISTRY-}budgets:${IMAGE_TAG}
      build:
        context: '.'
        dockerfile: 'Budgets/src/Budgets.Api/Dockerfile'
        args:
          - IMG_REGISTRY=${REGISTRY:-mcr.microsoft.com}
      environment:
        - ASPNETCORE_URLS=${ASPNETCORE_URLS:-https://*:4443}
      ports:
        - '43301:${EXPOSED_PORT:-4443}'
      volumes:
        - ~/.aspnet/https:/https:ro

**Comment by aaronscribner** [comment]
FYI, I stopped using this library and switched to writing json files. This is too buggy and requires too many hacks.

**Comment by rlidwka** [comment]
> If you read YAML and dump it, the content changes.

The content doesn't change. Only its representation does. Quotes in YAML are optional, so library may choose not to insert them.

js-yaml does not keep any information about original document (quotes, whitespace, comments) - these kind of things will get lost when dumping.

To keep that information, you'd need entirely different kind of library (not yaml loader, but yaml editor), and I'm not aware of any existing ones.

> FYI, I stopped using this library and switched to writing json files.

Uhh... please look at `yaml` library. Or toml file format. Or json5. Or any other format that is suited for the job.

Writing config files in json is an extremely poor decision, since json is a data serialization format, not a config file format. It should never be written by humans (verbose syntax, lack of comments, etc.).
